default: &default
  adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#
development:
  <<: *default
  database: yuga_rails_development
  username: <%= ENV.fetch("PGUSER") %>
  password: <%= ENV.fetch("PGPASSWORD") %>
  host: 127.0.0.1
  port: 5433
#
# test:
#   <<: *default
#   database: yuga_rails_test
#
# production:
#   <<: *default
#   database: yuga_rails_production
#   username: yuga_rails
#   password: <%= ENV['YUGA_RAILS_DATABASE_PASSWORD'] %>
